title: Alexander Cyon Consulting AB

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/864410

baseurl: "" # the subpath of your site, e.g. /blog

url: "cyonconsulting.github.io"
email: alex@cyonconsulting.com
github_username: sajjon
linkedin_username: alexcyon
twitter_username: AlexCyon

markdown: kramdown
theme: minima
exclude: [vendor]
